# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_inspireatomclient.ui'
#
# Created: Thu Nov 13 16:30:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InspireAtomClient(object):
    def setupUi(self, InspireAtomClient):
        InspireAtomClient.setObjectName(_fromUtf8("InspireAtomClient"))
        InspireAtomClient.resize(520, 725)
        self.lblUrl = QtGui.QLabel(InspireAtomClient)
        self.lblUrl.setGeometry(QtCore.QRect(20, 10, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblUrl.setFont(font)
        self.lblUrl.setObjectName(_fromUtf8("lblUrl"))
        self.txtUrl = QtGui.QLineEdit(InspireAtomClient)
        self.txtUrl.setGeometry(QtCore.QRect(20, 30, 481, 20))
        self.txtUrl.setObjectName(_fromUtf8("txtUrl"))
        self.frmMain = QtGui.QFrame(InspireAtomClient)
        self.frmMain.setGeometry(QtCore.QRect(0, 90, 521, 631))
        self.frmMain.setFrameShape(QtGui.QFrame.NoFrame)
        self.frmMain.setFrameShadow(QtGui.QFrame.Plain)
        self.frmMain.setObjectName(_fromUtf8("frmMain"))
        self.cmdGetFeed = QtGui.QPushButton(self.frmMain)
        self.cmdGetFeed.setGeometry(QtCore.QRect(20, 0, 161, 23))
        self.cmdGetFeed.setObjectName(_fromUtf8("cmdGetFeed"))
        self.cmdSelectDataset = QtGui.QPushButton(self.frmMain)
        self.cmdSelectDataset.setEnabled(False)
        self.cmdSelectDataset.setGeometry(QtCore.QRect(20, 90, 161, 23))
        self.cmdSelectDataset.setObjectName(_fromUtf8("cmdSelectDataset"))
        self.cmdMetadata = QtGui.QPushButton(self.frmMain)
        self.cmdMetadata.setEnabled(False)
        self.cmdMetadata.setGeometry(QtCore.QRect(190, 90, 161, 23))
        self.cmdMetadata.setObjectName(_fromUtf8("cmdMetadata"))
        self.cmbDatasets = QtGui.QComboBox(self.frmMain)
        self.cmbDatasets.setGeometry(QtCore.QRect(20, 60, 481, 22))
        self.cmbDatasets.setObjectName(_fromUtf8("cmbDatasets"))
        self.cmdDownload = QtGui.QPushButton(self.frmMain)
        self.cmdDownload.setEnabled(False)
        self.cmdDownload.setGeometry(QtCore.QRect(20, 570, 162, 23))
        self.cmdDownload.setObjectName(_fromUtf8("cmdDownload"))
        self.frmDataset = QtGui.QFrame(self.frmMain)
        self.frmDataset.setEnabled(False)
        self.frmDataset.setGeometry(QtCore.QRect(10, 150, 501, 411))
        self.frmDataset.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmDataset.setFrameShadow(QtGui.QFrame.Raised)
        self.frmDataset.setObjectName(_fromUtf8("frmDataset"))
        self.lblTitle = QtGui.QLabel(self.frmDataset)
        self.lblTitle.setGeometry(QtCore.QRect(10, 10, 501, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.lblInstance = QtGui.QLabel(self.frmDataset)
        self.lblInstance.setGeometry(QtCore.QRect(10, 190, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lblInstance.setFont(font)
        self.lblInstance.setObjectName(_fromUtf8("lblInstance"))
        self.cmbDatasetRepresentations = QtGui.QComboBox(self.frmDataset)
        self.cmbDatasetRepresentations.setGeometry(QtCore.QRect(10, 210, 481, 22))
        self.cmbDatasetRepresentations.setObjectName(_fromUtf8("cmbDatasetRepresentations"))
        self.lblId = QtGui.QLabel(self.frmDataset)
        self.lblId.setGeometry(QtCore.QRect(10, 100, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lblId.setFont(font)
        self.lblId.setObjectName(_fromUtf8("lblId"))
        self.lblRights = QtGui.QLabel(self.frmDataset)
        self.lblRights.setGeometry(QtCore.QRect(10, 140, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lblRights.setFont(font)
        self.lblRights.setObjectName(_fromUtf8("lblRights"))
        self.txtSummary = QtGui.QPlainTextEdit(self.frmDataset)
        self.txtSummary.setGeometry(QtCore.QRect(10, 30, 481, 51))
        self.txtSummary.setReadOnly(True)
        self.txtSummary.setObjectName(_fromUtf8("txtSummary"))
        self.txtId = QtGui.QPlainTextEdit(self.frmDataset)
        self.txtId.setGeometry(QtCore.QRect(120, 90, 371, 31))
        self.txtId.setReadOnly(True)
        self.txtId.setObjectName(_fromUtf8("txtId"))
        self.txtRights = QtGui.QPlainTextEdit(self.frmDataset)
        self.txtRights.setGeometry(QtCore.QRect(120, 130, 371, 41))
        self.txtRights.setReadOnly(True)
        self.txtRights.setObjectName(_fromUtf8("txtRights"))
        self.lblFiles = QtGui.QLabel(self.frmDataset)
        self.lblFiles.setGeometry(QtCore.QRect(10, 250, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lblFiles.setFont(font)
        self.lblFiles.setObjectName(_fromUtf8("lblFiles"))
        self.lwFiles = QtGui.QListWidget(self.frmDataset)
        self.lwFiles.setGeometry(QtCore.QRect(10, 270, 481, 131))
        self.lwFiles.setObjectName(_fromUtf8("lwFiles"))
        self.lblUrl_2 = QtGui.QLabel(self.frmMain)
        self.lblUrl_2.setGeometry(QtCore.QRect(20, 40, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblUrl_2.setFont(font)
        self.lblUrl_2.setObjectName(_fromUtf8("lblUrl_2"))
        self.lblUrl_3 = QtGui.QLabel(self.frmMain)
        self.lblUrl_3.setGeometry(QtCore.QRect(20, 130, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblUrl_3.setFont(font)
        self.lblUrl_3.setObjectName(_fromUtf8("lblUrl_3"))
        self.progressBar = QtGui.QProgressBar(self.frmMain)
        self.progressBar.setGeometry(QtCore.QRect(190, 570, 301, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lblMessage = QtGui.QLabel(self.frmMain)
        self.lblMessage.setGeometry(QtCore.QRect(20, 600, 481, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblMessage.setFont(font)
        self.lblMessage.setText(_fromUtf8(""))
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.chkAuthentication = QtGui.QCheckBox(InspireAtomClient)
        self.chkAuthentication.setGeometry(QtCore.QRect(20, 60, 261, 17))
        self.chkAuthentication.setObjectName(_fromUtf8("chkAuthentication"))
        self.txtUsername = QtGui.QLineEdit(InspireAtomClient)
        self.txtUsername.setGeometry(QtCore.QRect(120, 90, 381, 20))
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.lblPassword = QtGui.QLabel(InspireAtomClient)
        self.lblPassword.setGeometry(QtCore.QRect(20, 120, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName(_fromUtf8("lblPassword"))
        self.lblUsername = QtGui.QLabel(InspireAtomClient)
        self.lblUsername.setGeometry(QtCore.QRect(20, 90, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblUsername.setFont(font)
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.txtPassword = QtGui.QLineEdit(InspireAtomClient)
        self.txtPassword.setGeometry(QtCore.QRect(120, 120, 381, 20))
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))

        self.retranslateUi(InspireAtomClient)
        QtCore.QMetaObject.connectSlotsByName(InspireAtomClient)

    def retranslateUi(self, InspireAtomClient):
        InspireAtomClient.setWindowTitle(_translate("InspireAtomClient", "INSPIRE Atom Client 0.7.0", None))
        self.lblUrl.setText(_translate("InspireAtomClient", "INSPIRE ATOM Feed URL", None))
        self.txtUrl.setText(_translate("InspireAtomClient", "http://www.weichand.de/inspire/dls/verwaltungsgrenzen.xml", None))
        self.cmdGetFeed.setText(_translate("InspireAtomClient", "Get Metadata (Atom)", None))
        self.cmdSelectDataset.setText(_translate("InspireAtomClient", "Select from Map", None))
        self.cmdMetadata.setText(_translate("InspireAtomClient", "Metadata", None))
        self.cmdDownload.setText(_translate("InspireAtomClient", "Get Spatial Dataset", None))
        self.lblTitle.setText(_translate("InspireAtomClient", "Title", None))
        self.lblInstance.setText(_translate("InspireAtomClient", "Available Alternatives", None))
        self.lblId.setText(_translate("InspireAtomClient", "Resource Identifier", None))
        self.lblRights.setText(_translate("InspireAtomClient", "Rights", None))
        self.lblFiles.setText(_translate("InspireAtomClient", "Files", None))
        self.lblUrl_2.setText(_translate("InspireAtomClient", "Select Dataset", None))
        self.lblUrl_3.setText(_translate("InspireAtomClient", "Selected Dataset", None))
        self.chkAuthentication.setText(_translate("InspireAtomClient", "Authentication required", None))
        self.lblPassword.setText(_translate("InspireAtomClient", "Password", None))
        self.lblUsername.setText(_translate("InspireAtomClient", "Username", None))

